Rspec
ezeilo-su/enumerable_methods_in_ruby pull request #4
Opened 2020-05-20 11:19 UTC by ezeilo-su

This is a TDD (Test Driven Development) version of our Ruby's Enumerable Methods Project. RSpec version is implemented and documented in the readme file. We, therefore, request your review and comments so we can improve on our work. Thank you!

2020-05-20 18:14 UTC, shshamim63 requested changes
## Status :recycle: Required Changes :red_envelope: 
___
Hi @ezeilo-su and @Cathella :wave: 
You have gathered a lot of tests. But I think you have left some methods. Let's add them.
___
### :spades: Mandatory Changes :spades: 
___
1. Add some test for my_all?, my_any?, my_none?
2. Add test for my_each_with_index
3. Add some test for my_inject
___
##### Please add the following changes and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-05-20 18:14 UTC, shshamim63 commented on spec/enumerable_methods_spec.rb
> +  describe '#my_all?' do
Can you add a test where my_all? related to regex, of a certain class?

2020-05-20 18:14 UTC, shshamim63 commented on spec/enumerable_methods_spec.rb
> +  describe '#my_any?' do
Can you add a test where my_any? related to regex, of a certain class?

2020-05-20 18:14 UTC, shshamim63 commented on spec/enumerable_methods_spec.rb
> +  describe '#my_none?' do
Can you add a test where my_none? related to regex, of a certain class?

2020-05-21 03:52 UTC, serdg0 approved these changes
**Congratulations** @Cathella @ezeilo-su  :fireworks: :100: :fireworks:
Feel free to merge.

Great work writing those tests!

Keep the good work in your next project!
**Happy Coding!** :computer: :nerd_face:
**_Sergio Diaz_**

2020-05-21 07:47 UTC, merged